#!/usr/bin/env python3

import os
#import commands
import sys
import subprocess
#import psutil

def hook_func():
    sys.stdin = open("/dev/tty")
    
    #cmdline = '\x00'.join(psutil.Process(os.getppid()).cmdline)

    #if '\x00--author' in cmdline:
    #    print "skip the credential process on git-commit-checker"
    #    return 0
    
    name = subprocess.getoutput("git config --get user.name")
    address = subprocess.getoutput("git config --get user.email")
    identity = "nan"
    while not identity in ("", "Y", "y", "N", "n"):
        print("Author = %s <%s>" % (name, address))
        identity = input("Do you want to me to keep it this way? [Y/n] ")

    if (identity == "N" or identity == "n"):
        new_name = input("Username: ")
        new_address = input("Email: ")
        os.system("git config user.name \"%s\"" % new_name)
        os.system("git config user.email \"%s\"" % new_address)
        print("git-config update successfully")
        print("Please commit that again...")
        return 1

    return 0

sys.exit(hook_func())
